
package com.epam.web.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epam.web.service.Book;
import com.epam.web.service.LibraryWSResponse;
import com.epam.web.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryService", targetNamespace = "http://service.web.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryService {


    /**
     * 
     * @param newBook
     * @param oldBook
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse changeBook(
        @WebParam(name = "oldBook", partName = "oldBook")
        Book oldBook,
        @WebParam(name = "newBook", partName = "newBook")
        Book newBook);

    /**
     * 
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse getAllBooks();

    /**
     * 
     * @param bookName
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse getBookByName(
        @WebParam(name = "bookName", partName = "bookName")
        String bookName);

    /**
     * 
     * @param bookAuthor
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse getBooksByAuthor(
        @WebParam(name = "bookAuthor", partName = "bookAuthor")
        String bookAuthor);

    /**
     * 
     * @param bookToGiveBack
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse giveBackBook(
        @WebParam(name = "bookToGiveBack", partName = "bookToGiveBack")
        Book bookToGiveBack);

    /**
     * 
     * @param bookId
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse getBookById(
        @WebParam(name = "bookId", partName = "bookId")
        int bookId);

    
    /**
     * 
     * @param bookId
     * @return
     *     returns com.epam.web.service.LibraryWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LibraryWSResponse deleteBook(
        @WebParam(name = "bookId", partName = "bookId")
        int bookId);
}
